version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports: 
      - 6379 
    volumes:
        - ./volumes/redis_data:/data
    networks:
      - backend
  api:
    build:
      dockerfile: Dockerfile.Local
    restart: always
    ports:
      - 8802:8802
    volumes:
      - ./volumes/api_data:/opt/app/logs
    depends_on:
      - redis
    networks:
      - backend
networks:
  backend:
    name: backend_sample